version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.11.0"
    TF_COMMAND: "apply"
  parameter-store:
    AWS_ACCESS_KEY_ID: "/codebuild/MY_AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "/codebuild/MY_AWS_SECRET_ACCESS_KEY"

phases:
  install:
    runtime-versions:
      python: 3.9
    on-failure: ABORT
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    on-failure: ABORT
    commands:
      - cd "$CODEBUILD_SRC_DIR/terraform-manifests"
      - ls -lrt "$CODEBUILD_SRC_DIR/terraform-manifests"
      - terraform --version
      - terraform init -input=false --backend-config=stag.conf
      - terraform validate
      - terraform plan -lock=false -input=false -var-file=stag.tfvars
      - terraform $TF_COMMAND -input=false -var-file=stag.tfvars -auto-approve
  post_build:
    on-failure: CONTINUE
    commands:
      - echo terraform execution completed on `date`
